% Jared Li 4/4/18
% Goes through each .xlsx file generated by each trial of the VO2 system and places them all in one .mat file
% Data is saved as a 1xn structure.

% FOR PARVO EXCEL FILES: files must be saved with '.xlsx' format on your own
% computer before usage.

function[] = parvo_read(Patient_Name)

i = 0;
parvo_Excel = dir('*.xlsx')
filename = sprintf('%s.mat',Patient_Name)

for i = 1:length(parvo_Excel)
    
       [num,txt,raw] = xlsread(parvo_Excel(i).name);
       
       parvo_struct(i).filename = parvo_Excel(i).name;
       parvo_struct(i).numerical_data = num;
       parvo_struct(i).text_data = txt;
       parvo_struct(i).raw_data = raw;
        
end

save(filename,'parvo_struct')

fprintf('.mat file created successfully!\n')
end


