% Jared Li 2/22/18
% Goes through each .xlsx file generated by each trial of the VO2 system and places them all in one .mat file
% Data is saved as a 1xn structure.

function[] = VO2_read(Patient_Name)

i = 0;
VO2_Excel = dir('*.xlsx');
filename = sprintf('%s.mat',Patient_Name);

for i = 1:length(VO2_Excel)
    
       [num,txt,raw] = xlsread(VO2_Excel(i).name); 
       VO2_Struct(i).filename = VO2_Excel(i).name;
       VO2_Struct(i).numerical_data = num;
       VO2_Struct(i).text_data = txt;
       VO2_Struct(i).raw_data = raw;
        
end

save(filename,'VO2_Struct')

fprintf('.mat file created successfully!\n')
end


